ERROR - 2022-12-16 07:12:46 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_user' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095251_LogUser.php(38): CodeIgniter\Database\Forge->dropTable('log_user')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogUser->down()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(298): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\MigrateRollback.php(92): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 07:12:56 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_buku' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095243_LogBuku.php(12): CodeIgniter\Database\Forge->dropTable('log_buku')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogBuku->up()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 07:12:57 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_user' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095251_LogUser.php(11): CodeIgniter\Database\Forge->dropTable('log_user')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogUser->up()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 07:19:11 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_user' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095251_LogUser.php(38): CodeIgniter\Database\Forge->dropTable('log_user')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogUser->down()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(298): CodeIgniter\Database\MigrationRunner->migrate('down', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\MigrateRollback.php(92): CodeIgniter\Database\MigrationRunner->regress(0)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\MigrateRollback->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate:rollbac...', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 07:19:20 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_buku' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095243_LogBuku.php(12): CodeIgniter\Database\Forge->dropTable('log_buku')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogBuku->up()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 07:19:21 --> mysqli_sql_exception: Unknown table 'stylecod_pemweb.log_user' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('DROP TABLE `log...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('DROP TABLE `log...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('DROP TABLE `log...')
#3 D:\Haruman\ci4\system\Database\Forge.php(600): CodeIgniter\Database\BaseConnection->query('DROP TABLE `log...')
#4 D:\Haruman\ci4\app\Database\Migrations\2022-12-15-095251_LogUser.php(11): CodeIgniter\Database\Forge->dropTable('log_user')
#5 D:\Haruman\ci4\system\Database\MigrationRunner.php(868): App\Database\Migrations\LogUser->up()
#6 D:\Haruman\ci4\system\Database\MigrationRunner.php(187): CodeIgniter\Database\MigrationRunner->migrate('up', Object(stdClass))
#7 D:\Haruman\ci4\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}
ERROR - 2022-12-16 08:14:57 --> mysqli_sql_exception: MySQL server has gone away in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('SHOW COLUMNS FR...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('SHOW COLUMNS FR...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('SHOW COLUMNS FR...')
#3 D:\Haruman\ci4\system\Database\BaseConnection.php(1451): CodeIgniter\Database\BaseConnection->query('SHOW COLUMNS FR...')
#4 D:\Haruman\ci4\system\Commands\Database\ShowTableInfo.php(162): CodeIgniter\Database\BaseConnection->getFieldNames('bukutersedia')
#5 D:\Haruman\ci4\system\Commands\Database\ShowTableInfo.php(143): CodeIgniter\Commands\Database\ShowTableInfo->showDataOfTable('bukutersedia', 10, 15)
#6 D:\Haruman\ci4\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#7 D:\Haruman\ci4\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('db:table', Array)
#8 D:\Haruman\ci4\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#9 D:\Haruman\ci4\system\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#10 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#11 D:\Haruman\ci4\system\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\Haruman\ci4\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#13 D:\Haruman\ci4\spark(98): CodeIgniter\CLI\Console->run()
#14 {main}
CRITICAL - 2022-12-16 08:14:57 --> Call to a member function getResultArray() on bool
in SYSTEMPATH\Database\BaseConnection.php on line 1455.
 1 SYSTEMPATH\Commands\Database\ShowTableInfo.php(162): CodeIgniter\Database\BaseConnection->getFieldNames('bukutersedia')
 2 SYSTEMPATH\Commands\Database\ShowTableInfo.php(143): CodeIgniter\Commands\Database\ShowTableInfo->showDataOfTable('bukutersedia', 10, 15)
 3 SYSTEMPATH\CLI\Commands.php(63): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 4 SYSTEMPATH\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('db:table', [])
 5 SYSTEMPATH\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index([])
 6 SYSTEMPATH\CodeIgniter.php(920): CodeIgniter\CLI\CommandRunner->_remap('index', [...])
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
 8 SYSTEMPATH\CodeIgniter.php(347): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
10 ROOTPATH\spark(98): CodeIgniter\CLI\Console->run()
CRITICAL - 2022-12-16 08:15:21 --> Unsupported operand types: string + string
in APPPATH\Views\Trigger\index.php on line 27.
 1 SYSTEMPATH\View\View.php(213): include()
 2 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 3 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/index', [], true)
 4 APPPATH\Controllers\SemuaTrigger.php(21): view('trigger/index', [...])
 5 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->index()
 6 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 7 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:18:52 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:18:52 --> Invalid file: trigger/gagal.php
in SYSTEMPATH\Exceptions\FrameworkException.php on line 33.
 1 SYSTEMPATH\View\View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('trigger/gagal.php')
 2 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 3 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 4 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 5 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 6 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:21:18 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:21:18 --> Array to string conversion
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:21:46 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:21:46 --> Undefined variable $data
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:22:30 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:22:30 --> Undefined variable $data
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:24:25 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:24:25 --> Undefined variable $data
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $data', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:24:41 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:24:41 --> Array to string conversion
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(36): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:27:26 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:27:26 --> Array to string conversion
in APPPATH\Views\Trigger\gagal.php on line 12.
 1 APPPATH\Views\Trigger\gagal.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Array to string conversion', 'APPPATH\\Views\\Trigger\\gagal.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\gagal.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/gagal', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(37): view('trigger/gagal', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:29:05 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 08:33:44 --> mysqli_sql_exception: Table 'stylecod_pemweb.user' doesn't exist in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 08:34:44 --> Undefined variable $berhasil
in APPPATH\Views\Trigger\berhasil.php on line 12.
 1 APPPATH\Views\Trigger\berhasil.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $berhasil', 'APPPATH\\Views\\Trigger\\berhasil.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\berhasil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/berhasil', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(29): view('trigger/berhasil', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 08:36:43 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 08:38:02 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:03:07 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:03:27 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:03:47 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:03:49 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:04:42 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:04:49 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:05:03 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:05:19 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 11:05:30 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
CRITICAL - 2022-12-16 20:59:41 --> Undefined variable $error
in APPPATH\Views\Trigger\berhasil.php on line 12.
 1 APPPATH\Views\Trigger\berhasil.php(12): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $error', 'APPPATH\\Views\\Trigger\\berhasil.php', 12)
 2 SYSTEMPATH\View\View.php(213): include('APPPATH\\Views\\Trigger\\berhasil.php')
 3 SYSTEMPATH\View\View.php(216): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 4 SYSTEMPATH\Common.php(1134): CodeIgniter\View\View->render('trigger/berhasil', [], true)
 5 APPPATH\Controllers\SemuaTrigger.php(46): view('trigger/berhasil', [...])
 6 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
 7 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
 8 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
ERROR - 2022-12-16 21:00:57 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:01:09 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:02:16 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(45): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(58): App\Models\SemuaTriggerModel->log_insert_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->TriggerInsertUser()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:38 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:42 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(53): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(25): App\Models\SemuaTriggerModel->log_delete_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_delete_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:45 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(45): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(58): App\Models\SemuaTriggerModel->log_insert_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->TriggerInsertUser()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:47 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:49 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(61): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(42): App\Models\SemuaTriggerModel->log_update_user()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->log_update_user()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:52 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(69): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(74): App\Models\SemuaTriggerModel->transaksi_insert()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->transaksi_insert_Trigger()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:06:54 --> mysqli_sql_exception: PROCEDURE createUser already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE PROCEDUR...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE PROCEDUR...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE PROCEDUR...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(77): CodeIgniter\Database\BaseConnection->query('CREATE PROCEDUR...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(90): App\Models\SemuaTriggerModel->procedureCreateUser()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->procedureCreateUser()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:07:02 --> mysqli_sql_exception: Unknown column 'judul_buku' in 'NEW' in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(96): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(124): App\Models\SemuaTriggerModel->trigger_penambahan_buku()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_penambahan_buku()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
ERROR - 2022-12-16 21:08:11 --> mysqli_sql_exception: Trigger already exists in D:\Haruman\ci4\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 D:\Haruman\ci4\system\Database\MySQLi\Connection.php(292): mysqli->query('CREATE TRIGGER ...', 0)
#1 D:\Haruman\ci4\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('CREATE TRIGGER ...')
#2 D:\Haruman\ci4\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('CREATE TRIGGER ...')
#3 D:\Haruman\ci4\app\Models\SemuaTriggerModel.php(96): CodeIgniter\Database\BaseConnection->query('CREATE TRIGGER ...')
#4 D:\Haruman\ci4\app\Controllers\SemuaTrigger.php(124): App\Models\SemuaTriggerModel->trigger_penambahan_buku()
#5 D:\Haruman\ci4\system\CodeIgniter.php(927): App\Controllers\SemuaTrigger->trigger_penambahan_buku()
#6 D:\Haruman\ci4\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SemuaTrigger))
#7 D:\Haruman\ci4\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\Haruman\ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 D:\Haruman\ci4\system\Commands\Server\rewrite.php(46): require_once('D:\\Haruman\\ci4\\...')
#10 {main}
